/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.rav.bhaj.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This schema define the Employee object structure in Avro format */
@org.apache.avro.specific.AvroGenerated
public class Employee extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6794183433956095100L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Employee\",\"namespace\":\"com.rav.bhaj.kafka.avro.model\",\"doc\":\"This schema define the Employee object structure in Avro format\",\"fields\":[{\"name\":\"employeeId\",\"type\":\"int\"},{\"name\":\"employeeName\",\"type\":\"string\"},{\"name\":\"employeeCity\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Employee> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Employee> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Employee> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Employee> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Employee> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Employee to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Employee from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Employee instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Employee fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int employeeId;
  private java.lang.CharSequence employeeName;
  private java.lang.CharSequence employeeCity;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Employee() {}

  /**
   * All-args constructor.
   * @param employeeId The new value for employeeId
   * @param employeeName The new value for employeeName
   * @param employeeCity The new value for employeeCity
   */
  public Employee(java.lang.Integer employeeId, java.lang.CharSequence employeeName, java.lang.CharSequence employeeCity) {
    this.employeeId = employeeId;
    this.employeeName = employeeName;
    this.employeeCity = employeeCity;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return employeeId;
    case 1: return employeeName;
    case 2: return employeeCity;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: employeeId = (java.lang.Integer)value$; break;
    case 1: employeeName = (java.lang.CharSequence)value$; break;
    case 2: employeeCity = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'employeeId' field.
   * @return The value of the 'employeeId' field.
   */
  public int getEmployeeId() {
    return employeeId;
  }


  /**
   * Sets the value of the 'employeeId' field.
   * @param value the value to set.
   */
  public void setEmployeeId(int value) {
    this.employeeId = value;
  }

  /**
   * Gets the value of the 'employeeName' field.
   * @return The value of the 'employeeName' field.
   */
  public java.lang.CharSequence getEmployeeName() {
    return employeeName;
  }


  /**
   * Sets the value of the 'employeeName' field.
   * @param value the value to set.
   */
  public void setEmployeeName(java.lang.CharSequence value) {
    this.employeeName = value;
  }

  /**
   * Gets the value of the 'employeeCity' field.
   * @return The value of the 'employeeCity' field.
   */
  public java.lang.CharSequence getEmployeeCity() {
    return employeeCity;
  }


  /**
   * Sets the value of the 'employeeCity' field.
   * @param value the value to set.
   */
  public void setEmployeeCity(java.lang.CharSequence value) {
    this.employeeCity = value;
  }

  /**
   * Creates a new Employee RecordBuilder.
   * @return A new Employee RecordBuilder
   */
  public static com.rav.bhaj.kafka.avro.model.Employee.Builder newBuilder() {
    return new com.rav.bhaj.kafka.avro.model.Employee.Builder();
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.rav.bhaj.kafka.avro.model.Employee.Builder newBuilder(com.rav.bhaj.kafka.avro.model.Employee.Builder other) {
    if (other == null) {
      return new com.rav.bhaj.kafka.avro.model.Employee.Builder();
    } else {
      return new com.rav.bhaj.kafka.avro.model.Employee.Builder(other);
    }
  }

  /**
   * Creates a new Employee RecordBuilder by copying an existing Employee instance.
   * @param other The existing instance to copy.
   * @return A new Employee RecordBuilder
   */
  public static com.rav.bhaj.kafka.avro.model.Employee.Builder newBuilder(com.rav.bhaj.kafka.avro.model.Employee other) {
    if (other == null) {
      return new com.rav.bhaj.kafka.avro.model.Employee.Builder();
    } else {
      return new com.rav.bhaj.kafka.avro.model.Employee.Builder(other);
    }
  }

  /**
   * RecordBuilder for Employee instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Employee>
    implements org.apache.avro.data.RecordBuilder<Employee> {

    private int employeeId;
    private java.lang.CharSequence employeeName;
    private java.lang.CharSequence employeeCity;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.rav.bhaj.kafka.avro.model.Employee.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.employeeId)) {
        this.employeeId = data().deepCopy(fields()[0].schema(), other.employeeId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.employeeName)) {
        this.employeeName = data().deepCopy(fields()[1].schema(), other.employeeName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.employeeCity)) {
        this.employeeCity = data().deepCopy(fields()[2].schema(), other.employeeCity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Employee instance
     * @param other The existing instance to copy.
     */
    private Builder(com.rav.bhaj.kafka.avro.model.Employee other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.employeeId)) {
        this.employeeId = data().deepCopy(fields()[0].schema(), other.employeeId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.employeeName)) {
        this.employeeName = data().deepCopy(fields()[1].schema(), other.employeeName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.employeeCity)) {
        this.employeeCity = data().deepCopy(fields()[2].schema(), other.employeeCity);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'employeeId' field.
      * @return The value.
      */
    public int getEmployeeId() {
      return employeeId;
    }


    /**
      * Sets the value of the 'employeeId' field.
      * @param value The value of 'employeeId'.
      * @return This builder.
      */
    public com.rav.bhaj.kafka.avro.model.Employee.Builder setEmployeeId(int value) {
      validate(fields()[0], value);
      this.employeeId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeId' field has been set.
      * @return True if the 'employeeId' field has been set, false otherwise.
      */
    public boolean hasEmployeeId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'employeeId' field.
      * @return This builder.
      */
    public com.rav.bhaj.kafka.avro.model.Employee.Builder clearEmployeeId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeName' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmployeeName() {
      return employeeName;
    }


    /**
      * Sets the value of the 'employeeName' field.
      * @param value The value of 'employeeName'.
      * @return This builder.
      */
    public com.rav.bhaj.kafka.avro.model.Employee.Builder setEmployeeName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.employeeName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeName' field has been set.
      * @return True if the 'employeeName' field has been set, false otherwise.
      */
    public boolean hasEmployeeName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'employeeName' field.
      * @return This builder.
      */
    public com.rav.bhaj.kafka.avro.model.Employee.Builder clearEmployeeName() {
      employeeName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'employeeCity' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmployeeCity() {
      return employeeCity;
    }


    /**
      * Sets the value of the 'employeeCity' field.
      * @param value The value of 'employeeCity'.
      * @return This builder.
      */
    public com.rav.bhaj.kafka.avro.model.Employee.Builder setEmployeeCity(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.employeeCity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'employeeCity' field has been set.
      * @return True if the 'employeeCity' field has been set, false otherwise.
      */
    public boolean hasEmployeeCity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'employeeCity' field.
      * @return This builder.
      */
    public com.rav.bhaj.kafka.avro.model.Employee.Builder clearEmployeeCity() {
      employeeCity = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Employee build() {
      try {
        Employee record = new Employee();
        record.employeeId = fieldSetFlags()[0] ? this.employeeId : (java.lang.Integer) defaultValue(fields()[0]);
        record.employeeName = fieldSetFlags()[1] ? this.employeeName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.employeeCity = fieldSetFlags()[2] ? this.employeeCity : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Employee>
    WRITER$ = (org.apache.avro.io.DatumWriter<Employee>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Employee>
    READER$ = (org.apache.avro.io.DatumReader<Employee>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeInt(this.employeeId);

    out.writeString(this.employeeName);

    out.writeString(this.employeeCity);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.employeeId = in.readInt();

      this.employeeName = in.readString(this.employeeName instanceof Utf8 ? (Utf8)this.employeeName : null);

      this.employeeCity = in.readString(this.employeeCity instanceof Utf8 ? (Utf8)this.employeeCity : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.employeeId = in.readInt();
          break;

        case 1:
          this.employeeName = in.readString(this.employeeName instanceof Utf8 ? (Utf8)this.employeeName : null);
          break;

        case 2:
          this.employeeCity = in.readString(this.employeeCity instanceof Utf8 ? (Utf8)this.employeeCity : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










